### ISSUE TITLE
Get up to speed on code

### ISSUE THREAD

**Issue by jacob-meacham** [jacob-meacham/galactic-ansible#1]
@nsimonson I'm not wed to any of this code at all - it was written a while ago.

We should also probably spend an hour modernizing the infrastructure here. In particular, now that modern node supports most of es6, we can rip out a lot of the babel transforms. I'm happy to do this

**Comment by nsimonson** [comment]
Can't get some of the scripts to run. `dependency-check package.json --entry src/` is failing for me.

<details>
  <summary>Console output</summary><p>

  ```
/Users/Niko/Source/galactic-ansible/node_modules/acorn/dist/acorn.js:2490
  throw err
  ^

SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (1:0)
    at Parser.pp$4.raise (/Users/Niko/Source/galactic-ansible/node_modules/acorn/dist/acorn.js:2488:13)
    at Parser.pp$1.parseStatement (/Users/Niko/Source/galactic-ansible/node_modules/acorn/dist/acorn.js:762:14)
    at Parser.pp$1.parseTopLevel (/Users/Niko/Source/galactic-ansible/node_modules/acorn/dist/acorn.js:672:23)
    at Parser.parse (/Users/Niko/Source/galactic-ansible/node_modules/acorn/dist/acorn.js:529:15)
    at Object.parse (/Users/Niko/Source/galactic-ansible/node_modules/acorn/dist/acorn.js:3378:37)
    at parse (/Users/Niko/Source/galactic-ansible/node_modules/detective/index.js:9:18)
    at Function.exports.find (/Users/Niko/Source/galactic-ansible/node_modules/detective/index.js:44:15)
    at module.exports (/Users/Niko/Source/galactic-ansible/node_modules/detective/index.js:23:20)
    at read (/Users/Niko/Source/galactic-ansible/node_modules/dependency-check/index.js:171:22)
    at tryToString (fs.js:455:3)
```
</p></details>

**Comment by jacob-meacham** [comment]
Stupidly, I didn't peg dependencies in this repo. I'll peg dependencies and then we can decide whether to update them

**Comment by nsimonson** [comment]
Sounds good. I can check in a yarn.lock file too which accomplishes something similar... if you're using yarn.

**Comment by jacob-meacham** [comment]
yeah, I'm not opposed to yarn, but explicitly pegging dependencies in package.json is still the right move, imo
